mode: live
start_date: 2025-04-01
end_date: 2025-08-24
primary_interval: 15m
initial_cash: 100000
margin_requirement: 0.0
show_reasoning: false
show_agent_graph: true
live_poll_seconds: 0  # 0 = align to bar closes in live mode
notify_every_steps: 1  # backtest: send summary every N steps
notify_enabled: true
notify_skip_hold: true
notify_live_trade_cooldown_seconds: 300
notify_live_summary_seconds: 900   # gửi summary mỗi 15 phút
signals:
  intervals: ["15m", "1h", "4h", "1d"]
  tickers: ["BTCUSDT", "ETHUSDT"]
  strategies: ['MTFTrendEntryStrategy']
model:
  name: "gpt-4o-mini" # config your model
  provider: "openai"  # config your llm provider, support openai， groq， openrouter，gemini，anthropic，ollama
  base_url: "https://api.openai.com/v1"  # not required, but if you want to set the base_url
# model:
#   name: "openai/gpt-oss-20b"  # Model mới của OpenAI trên Groq
#   provider: "groq"             # Đổi provider thành groq
#   base_url: "https://api.groq.com"  # URL của Groq API

